# Generated by Django 2.0.1 on 2018-12-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birja', '0003_auto_20181219_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
